# Generated by Django 3.2.12 on 2022-04-16 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('achievement_type', models.CharField(choices=[('Membership', 'membership'), ('Achievement', 'achievement'), ('Award', 'award')], max_length=20)),
                ('organization', models.CharField(max_length=50)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('father_name', models.CharField(max_length=250)),
                ('mother_name', models.CharField(max_length=250)),
                ('nationality', models.CharField(max_length=30)),
                ('nid_passport_no', models.CharField(max_length=250)),
                ('is_employed', models.BooleanField()),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('phone_number', models.CharField(max_length=13)),
                ('work_phone', models.CharField(blank=True, max_length=13, null=True)),
                ('photo', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[300, 300], upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=50)),
                ('passing_year', models.CharField(blank=True, max_length=4, null=True)),
                ('area_major', models.CharField(max_length=50)),
                ('division_class_cgpa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=50)),
                ('major_responsibilities', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivements', models.ManyToManyField(to='profiles.AchievementMembership')),
                ('basic_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.basicinfo')),
                ('educational_background', models.ManyToManyField(to='profiles.EducationalBackground')),
                ('test_score', models.ManyToManyField(to='profiles.TestScore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_experience', models.ManyToManyField(to='profiles.WorkExperience')),
            ],
        ),
    ]
