# Generated by Django 3.2.12 on 2022-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220420_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='test',
            field=models.CharField(choices=[('GMAT', 'GMAT'), ('GRE', 'GRE'), ('TOEFL', 'TOEFL'), ('IELTS', 'IELTS')], max_length=10),
        ),
    ]
