# Generated by Django 3.2.12 on 2022-04-30 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_alter_testscore_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalbackground',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_background', related_query_name='educational_background', to=settings.AUTH_USER_MODEL),
        ),
    ]
