# Generated by Django 3.2.12 on 2022-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_educationalbackground_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
