# Generated by Django 3.2.12 on 2022-11-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_workexperience_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalbackground',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='educationalbackground',
            name='division_class_cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='major_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
