# Generated by Django 3.2.12 on 2022-11-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20221101_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementmembership',
            name='achievement_type',
            field=models.CharField(choices=[('Membership', 'Membership'), ('Achievement', 'Achievement'), ('Award', 'Award')], max_length=20),
        ),
    ]
