# Generated by Django 3.2.12 on 2022-11-17 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_basicinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscore',
            name='test_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
