# Generated by Django 3.2.12 on 2022-11-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_testscore_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementmembership',
            name='year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='from_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='to_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
