# Generated by Django 3.2.12 on 2022-11-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_workexperience_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='score',
            field=models.CharField(max_length=250),
        ),
    ]
