# Generated by Django 3.2.12 on 2022-12-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_testscore_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementmembership',
            options={'ordering': ('-year',)},
        ),
        migrations.AlterModelOptions(
            name='educationalbackground',
            options={'ordering': ('-passing_year',)},
        ),
    ]
