# Generated by Django 3.2.12 on 2022-04-30 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call_applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_payment_done', models.BooleanField(default=False)),
                ('call_for_application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='call_applications.callforapplication')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
