# Generated by Django 3.2.12 on 2022-05-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gw_trx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
