# Generated by Django 3.2.12 on 2022-07-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_call_for_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='data',
            field=models.JSONField(editable=False),
        ),
    ]
