# Generated by Django 3.2.12 on 2022-07-04 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('call_applications', '0002_callforapplication_shortcode'),
        ('applications', '0004_alter_application_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='roll_no',
            field=models.CharField(default='0001', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('call_for_application', 'user')},
        ),
    ]
