# Generated by Django 3.2.12 on 2022-07-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20220704_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='seat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
