# Generated by Django 3.2.12 on 2022-07-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_seat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
