# Generated by Django 3.2.12 on 2022-11-03 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0007_alter_application_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('Manual', 'Manual'), ('Gateway', 'Gateway')], max_length=10)),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_time', models.CharField(max_length=30)),
                ('is_approved', models.BooleanField(default=False)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
