# Generated by Django 3.2.12 on 2022-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_from',
            field=models.CharField(default='Bkash', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_method',
            field=models.CharField(default='Bkash', max_length=50),
            preserve_default=False,
        ),
    ]
