# Generated by Django 3.2.12 on 2022-11-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20221109_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactin_amount',
            field=models.CharField(default=520, max_length=20),
            preserve_default=False,
        ),
    ]
