# Generated by Django 3.2.12 on 2022-11-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_transaction_transactin_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transactin_amount',
            new_name='amount',
        ),
    ]
