# Generated by Django 3.2.12 on 2022-11-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_rename_transactin_amount_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateField(max_length=30),
        ),
    ]
