# Generated by Django 3.2.12 on 2022-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_transaction_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_admit_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_seatplan_ready',
            field=models.BooleanField(default=False),
        ),
    ]
