# Generated by Django 3.2.12 on 2022-11-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20221115_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
    ]
