# Generated by Django 3.2.12 on 2022-11-16 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_transaction_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.seat'),
        ),
    ]
