# Generated by Django 3.2.12 on 2022-11-17 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20221116_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.transaction'),
        ),
    ]
