# Generated by Django 3.2.12 on 2022-11-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_applications', '0004_remove_callforapplication_is_open'),
        ('applications', '0016_auto_20221117_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='call_for_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='call_applications.callforapplication'),
        ),
    ]
