# Generated by Django 3.2.12 on 2022-12-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_auto_20221202_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('result', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
