# Generated by Django 3.2.12 on 2022-12-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_asyncresults'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsyncResults',
        ),
    ]
