# Generated by Django 3.2.12 on 2022-07-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callforapplication',
            name='shortcode',
            field=models.CharField(default='2022', max_length=10),
            preserve_default=False,
        ),
    ]
