# Generated by Django 3.2.12 on 2022-11-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_applications', '0002_callforapplication_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callforapplication',
            name='shortcode',
            field=models.CharField(max_length=20),
        ),
    ]
