# Generated by Django 3.2.12 on 2022-11-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_applications', '0003_alter_callforapplication_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callforapplication',
            name='is_open',
        ),
    ]
