# Generated by Django 3.2.12 on 2022-12-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_applications', '0004_remove_callforapplication_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='callforapplication',
            name='chunk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callforapplication',
            name='exam_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='callforapplication',
            name='viva_voce_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='callforapplication',
            name='written_exam_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
