# Generated by Django 3.2.12 on 2022-12-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_applications', '0005_auto_20221202_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='callforapplication',
            name='skip_to',
            field=models.IntegerField(default=100),
        ),
    ]
