# Generated by Django 3.0.4 on 2020-04-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile_no', models.CharField(max_length=20, unique=True, verbose_name='Mobile No')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=30)),
                ('user_type', models.CharField(choices=[('0', 'Client'), ('1', 'Member'), ('2', 'Admin')], help_text="'0' for client, '1' for member, '2' for Admin", max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
